highlighter: rouge
timezone: America/New_York
encoding: utf-8
title: Binghamton ACM
domain: "http://binghamtonacm.com"

facebook-url: "https://www.facebook.com/BinghamtonACM"

safe: true
lsi: false
source: .
